apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-web-server
spec:
  selector:
    matchLabels:
      k8s-app: simple-web-server
  replicas: 4
  template:
    metadata:
      labels:
        k8s-app: simple-web-server
    spec:
      containers:
      - image: alcheagle/simple_web_server
        name: simple-web-server
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: simple-web-server
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    k8s-app: simple-web-server

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: simple-web-server
spec:
  rules:
    - http:
        paths:
        - path: /simple_web_server
          backend:
            serviceName: simple-web-server
            servicePort: 8080
